## Laboratorium 2

In [107]:
import numpy as np

### Zadanie 1

In [43]:
def findMax(tab, l): # return iterator

    max_num = float("-inf")
    current_i = l

    for i in range(l, len(tab)):
        if tab[i][l] > max_num:
            current_i = i
            max_num = tab[i][l]

    return current_i


In [44]:
def solverGaussJordan(A, B):
    n = len(A)

    a = A.copy()
    b = B.copy()
    
    a = np.column_stack((a, b))

    for i in range(n):

        switch_i = findMax(a, i)
        a[[i, switch_i], :] = a [[switch_i, i], :]
        # print(a)
        
        for k in range(i):
            # print(i)
            a[k] = (-1) * (a[k][i] / a[i][i]) * a[i] + a[k]
            a[k][i] = 0.0

        for k in range(i+1, n):
            a[k] = (-1) * (a[k][i] / a[i][i]) * a[i] + a[k]
            a[k][i] = 0.0
    for i in range(n):
        tmp = a[i][i]
        a[i][n] /= tmp
        a[i][i] /= tmp
        

    solve = np.ones((n,1), dtype=np.float64)
    for i in range(n):
        solve[i][0] *= a[i][n]
    # print(a) # skasować gdy 500 albo wiecej
    return solve
    


In [45]:
a = np.array([(1, 2, 3),
              (4, 5, 6),
              (7, 8, 9)], dtype=np.float64)
b = np.array([(1,),
              (2,),
              (3,)], np.float64)

# Dla 500
# A = np.random.uniform(0,10, (500, 500))
# B = np.random.uniform(0,10, (500,1))

A = np.random.uniform(0,10, (3, 3))
B = np.random.uniform(0,10, (3,1))


In [46]:
def gaussJordanTimes(a, b):
    time_s = 0
    n = len(a)
    # print(n)
    
    time_s = time.perf_counter()
    result1 = solverGaussJordan(a, b)
    time_gs = time.perf_counter() - time_s

    time_s = time.perf_counter()
    result2 = np.linalg.solve(a, b)
    time_np_solve = time.perf_counter() - time_s
    
    if np.allclose(result1, result2):
        print("Times for {length}x{length} matrix: \n\
GaussJordan solve: {GJ}   numpy solve: {np_solve}".format(length = n, GJ = time_gs, np_solve = time_np_solve))

    else:
        print("Błędnie wyliczony wynik.")

In [47]:
result1 = solverGaussJordan(A, B)
np_result1 = np.linalg.solve(A,B)
print(np.allclose(np_result1, result1))
print(result1)

True
[[ 0.57305543]
 [-1.08853946]
 [ 1.53375781]]


Porównanie czasu wykonania własno-zaimplementowanego algorytmu z algorytmem z biblioteki numpy


In [48]:
n = 100
table_len = 15
A = [np.random.randint(0, 100, (n * i, n * i)).astype(np.float64) for i in range(1, table_len + 1)]
B = [np.random.randint(0, 100, (n * i, 1)).astype(np.float64) for i in range(1, table_len + 1)]

In [49]:
for i in range(table_len):
    gaussJordanTimes(A[i], B[i])

Times for 100x100 matrix: 
GaussJordan solve: 0.036637573000916746   numpy solve: 0.004747646002215333
Times for 200x200 matrix: 
GaussJordan solve: 0.1875658420030959   numpy solve: 0.0034928140012198128
Times for 300x300 matrix: 
GaussJordan solve: 0.3699661790014943   numpy solve: 0.005058857997937594
Times for 400x400 matrix: 
GaussJordan solve: 0.6171341999943252   numpy solve: 0.0025139939971268177
Times for 500x500 matrix: 
GaussJordan solve: 0.9939114760054508   numpy solve: 0.005645241995807737
Times for 600x600 matrix: 
GaussJordan solve: 1.5815800679993117   numpy solve: 0.005872854002518579
Times for 700x700 matrix: 
GaussJordan solve: 2.2510914059967035   numpy solve: 0.028719287998683285
Times for 800x800 matrix: 
GaussJordan solve: 3.1101107249996858   numpy solve: 0.026243427004374098
Times for 900x900 matrix: 
GaussJordan solve: 4.003157038001518   numpy solve: 0.02066299699799856
Times for 1000x1000 matrix: 
GaussJordan solve: 5.074650073001976   numpy solve: 0.018289

KeyboardInterrupt: 

### Zadanie 2 - faktoryzacja

In [101]:
def factorization(A):
    a = A.copy().astype(np.float64)
    n = len(A)
    for i in range(n):
        for j in range(i+1, n):
            x = a[j][i] / a[i][i]
            a[j, i:] = (-1) * x * a[i, i:] + a[j, i:]
            a[j][i] = -x
    L = np.tril(a)
    np.fill_diagonal(L, 1)
    U = np.triu(a)
    return L, U

In [51]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], dtype=np.float64)

In [ ]:
a[1:,1:] /= 3.0
a

array([[1.        , 2.        , 3.        ],
       [4.        , 1.66666667, 2.        ],
       [7.        , 2.66666667, 3.        ]])

In [40]:
# np.triu(a)
np.tril(a)
# np.fill_diagonal(a, 1)


array([[1., 0., 0.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [79]:
b = np.array([[2,2,2],
              [4,7,7],
              [6,18,22]], dtype=np.float64)

In [108]:
# b_factor= factorization(b)
l1, u1= factorization(b)

