## Laboratorium 2

In [2]:
import numpy as np

### Zadanie 1

In [22]:
def findMax(tab, l): # return iterator

    max_num = float("-inf")
    current_i = l

    for i in range(l, len(tab)):
        if tab[i][l] > max_num:
            current_i = i
            max_num = tab[i][l]

    return current_i


In [83]:
def solverGaussJordan(A, B):
    n = len(A)

    a = A.copy()
    b = B.copy()
    
    a = np.column_stack((a, b))

    for i in range(n):

        switch_i = findMax(a, i)
        a[[i, switch_i], :] = a [[switch_i, i], :]
        # print(a)
        
        for k in range(i):
            # print(i)
            a[k] = (-1) * (a[k][i] / a[i][i]) * a[i] + a[k]
            a[k][i] = 0.0

        for k in range(i+1, n):
            a[k] = (-1) * (a[k][i] / a[i][i]) * a[i] + a[k]
            a[k][i] = 0.0
    for i in range(n):
        tmp = a[i][i]
        a[i][n] /= tmp
        a[i][i] /= tmp
        

    solve = np.ones((n,1), dtype=np.float64)
    for i in range(n):
        solve[i][0] *= a[i][n]
    print(a) # skasować gdy 500 albo wiecej
    return solve
    


In [84]:
a = np.array([(1, 2, 3),
              (4, 5, 6),
              (7, 8, 9)], dtype=np.float64)
b = np.array([(1,),
              (2,),
              (3,)], np.float64)

# Dla 500
# A = np.random.uniform(0,10, (500, 500))
# B = np.random.uniform(0,10, (500,1))

A = np.random.uniform(0,10, (3, 3))
B = np.random.uniform(0,10, (3,1))


In [85]:
result1 = solverGaussJordan(A, B)
np_result1 = np.linalg.solve(A,B)
print(np.allclose(np_result1, result1))
print(result1)

[[ 1.          0.          0.         -0.44060547]
 [ 0.          1.          0.          1.34493449]
 [ 0.          0.          1.          0.13525461]]
True
[[-0.44060547]
 [ 1.34493449]
 [ 0.13525461]]
